import type { Conteudo } from "./tipos";

/* English. Mirrors src/conteudo/pt.ts. */
export const en: Conteudo = {
  meta: {
    titulo: "Códice · Turn your store space into revenue",
    descricao:
      "Códice rents smart displays for R$ 499 a month. Your chain sells the exposure week to brands, with display, maintenance and platform included.",
    palavras: "retail media, in store display, display rental, shopper marketing, trade marketing",
    ogAlt: "Códice display installed in a supermarket",
  },
  nav: {
    links: [
      { id: "como", rotulo: "How it works" },
      { id: "plataforma", rotulo: "Platform" },
      { id: "displays", rotulo: "Displays" },
      { id: "planos", rotulo: "Plans" },
      { id: "conta", rotulo: "Simulator" },
    ],
    cta: "Talk to a specialist",
    abrirMenu: "Open menu",
    fecharMenu: "Close menu",
    idioma: "Language",
    irParaConteudo: "Skip to content",
  },
  heroi: {
    chapeu: "Retail media for store chains",
    titulo: ["Turn your store space into", "revenue every month"],
    lead: "Códice installs and maintains the display. Your chain sells the exposure week to brands.",
    ctaPrimario: "Talk to a specialist",
    ctaSecundario: "Simulate my chain",
    selos: [
      { valor: "R$ 499", rotulo: "per display, per month" },
      { valor: "1 slot", rotulo: "pays 3 months of rent" },
      { valor: "R$ 0", rotulo: "upfront investment" },
    ],
    legendaFoto: "Códice display installed in a supermarket",
  },
  prova: {
    frase: "Own factory with 40 years of point of sale work and more than 15,000 stores served by the group.",
    marcas: "Brands the group companies already serve",
  },
  como: {
    chapeu: "How it works",
    titulo: "Three steps, one contract",
    passos: [
      { n: "01", icone: "ferramenta", titulo: "We install", texto: "Design, production and in store assembly, with no entry cost.", foto: "/fotos/foto-instalacao.jpg", alt: "Technical team installing the display in the store" },
      { n: "02", icone: "calendario", titulo: "Your chain sells", texto: "The brand buys the week with the creative included.", foto: "/fotos/foto-ilha-supermercado.jpg", alt: "Códice display carrying a brand campaign in a supermarket" },
      { n: "03", icone: "grafico", titulo: "We maintain and measure", texto: "Maintenance, artwork swaps and reports with proof of execution.", foto: "/fotos/foto-monitoramento.jpg", alt: "Monitoring centre following the operation" },
    ],
    regra: "1 slot = 1 week of 1 display",
  },
  entrega: {
    chapeu: "What is included",
    titulo: "Everything in the same monthly fee",
    lead: "No project, maintenance or software costs on the side.",
    itens: [
      { icone: "display", titulo: "The display", texto: "Design, manufacturing and assembly." },
      { icone: "ferramenta", titulo: "Maintenance", texto: "Preventive visits and repairs included." },
      { icone: "calendario", titulo: "Creative swaps", texto: "New artwork every campaign." },
      { icone: "grafico", titulo: "Platform", texto: "Calendar, booking and reporting." },
      { icone: "sensor", titulo: "Measurement", texto: "Traffic and proof of play." },
      { icone: "pessoas", titulo: "Sales support", texto: "Rate card and sales material." },
    ],
  },
  plataforma: {
    chapeu: "Platform",
    titulo: "Your media operation on one screen",
    lead: "Calendar, campaigns, fleet and results in the same place.",
    telas: [
      { arquivo: "sis-painel", nome: "Dashboard", texto: "Occupancy, revenue and deadlines for the week." },
      { arquivo: "sis-inventario", nome: "Inventory", texto: "Every display becomes weekly slots." },
      { arquivo: "sis-campanhas", nome: "Campaigns", texto: "From booking to going live." },
      { arquivo: "sis-sensores", nome: "Sensors", texto: "Traffic measured store by store." },
      { arquivo: "sis-mapa", nome: "Fleet map", texto: "Every display on the map." },
      { arquivo: "sis-excecoes", nome: "Exceptions", texto: "Anything off plan becomes a task." },
      { arquivo: "sis-campo", nome: "Field mode", texto: "Inspection from the phone, with QR." },
    ],
    ampliar: "Enlarge",
    fechar: "Close",
    anterior: "Previous",
    proxima: "Next",
    aviso: "Real screens from the system, with demo data.",
  },
  displays: {
    chapeu: "Displays",
    titulo: "Six formats, made in Brazil",
    lead: "Modular structure with creative swapped every campaign.",
    instrucao: "Drag to spin",
    formatos: [
      { id: "essencial", rotulo: "End cap", nome: "Gondola end cap", texto: "The most contested spot in the store.", medidas: "202 × 104 × 55 cm" },
      { id: "ilha", rotulo: "Island", nome: "Double sided island", texto: "Two selling faces for wide aisles.", medidas: "190 × 120 × 96 cm" },
      { id: "painel", rotulo: "Panel", nome: "Accessory panel", texto: "Hooks for small, high value items.", medidas: "195 × 122 × 42 cm" },
      { id: "vitrine", rotulo: "Cabinet", nome: "Premium cabinet", texto: "Glass that protects the product and lifts the slot value.", medidas: "192 × 122 × 54 cm" },
      { id: "categoria", rotulo: "Category", nome: "Category stand", texto: "Shelves with a brand band at the base.", medidas: "200 × 100 × 46 cm" },
      { id: "multiuso", rotulo: "Multi use", nome: "Multi use with drawers", texto: "Display on top, backup stock below.", medidas: "195 × 74 × 52 cm" },
    ],
  },
  planos: {
    chapeu: "Plans",
    titulo: "Choose how much the display should measure",
    lead: "The more the display proves, the more the chain charges per slot.",
    porMes: "per display, per month",
    itens: [
      {
        id: "essencial", nome: "Essencial", preco: 499, selo: "To start", quem: "Start selling space with low complexity.",
        recursos: [
          { icone: "display", texto: "Modular display" },
          { icone: "calendario", texto: "Swappable creative" },
          { icone: "qr", texto: "Asset QR code" },
          { icone: "ferramenta", texto: "Maintenance included" },
        ],
      },
      {
        id: "sense", nome: "Sense", preco: 849, selo: "Most chosen", quem: "High traffic spots, with proof of passage.",
        recursos: [
          { icone: "check", texto: "Everything in Essencial" },
          { icone: "pessoas", texto: "Proximity sensor" },
          { icone: "wifi", texto: "Connection alerts" },
          { icone: "grafico", texto: "Execution dashboard" },
        ],
      },
      {
        id: "media", nome: "Media", preco: 1290, selo: "Highest value per slot", quem: "Launches and campaigns with in store video.",
        recursos: [
          { icone: "check", texto: "Everything in Sense" },
          { icone: "tela", texto: "Screen and player" },
          { icone: "calendario", texto: "Remote content" },
          { icone: "escudo", texto: "Proof of play" },
        ],
      },
    ],
    cta: "I want this plan",
    nota: "Installation, maintenance and platform included in every plan.",
  },
  conta: {
    chapeu: "The numbers",
    titulo: "Subscribing costs 86% less in month one",
    lead: "Buying demands capital before the first sale. Subscribing does not.",
    comprar: { titulo: "Buying on your own", valor: 3620, nota: "Display, installation and operation in month 1." },
    assinar: { titulo: "Subscribing to Códice", valor: 499, nota: "All inclusive, no capital tied up.", selo: "86% less" },
    grafico: {
      titulo: "Accumulated outlay per display, over 12 months",
      serieComprar: "Buying on your own",
      serieAssinar: "Subscribing to Códice",
      virada: "Buying starts to accumulate less",
      mes: "M",
    },
    argumento: [
      "No capital parked before the first slot is sold.",
      "Maintenance, artwork swaps and platform always included.",
      "Technology that evolves by layer, with no new purchase.",
    ],
    simulador: {
      titulo: "Simulate your chain",
      campos: { lojas: "Stores", displays: "Displays per store", cota: "Slot price", ocupacao: "Calendar sold" },
      saidas: { receita: "Revenue from slots", aluguel: "Códice rent", lucro: "Profit over 12 months" },
      periodo: "12 month projection",
      nota: "Figures before tax. Average month of 4.3 weeks.",
      cta: "Send this simulation",
    },
  },
  numeros: {
    itens: [
      { valor: 40, sufixo: "+", rotulo: "years of manufacturing" },
      { valor: 15000, sufixo: "+", rotulo: "stores served by the group" },
      { valor: 6, sufixo: "", rotulo: "display formats" },
      { valor: 100, sufixo: "%", rotulo: "produced in Brazil" },
    ],
    nota: "Figures from the group companies: NeoBand in manufacturing and 75 LAB in trade and technology.",
  },
  faq: {
    chapeu: "FAQ",
    titulo: "What people ask before signing",
    itens: [
      { pergunta: "Do we need to buy anything to start?", resposta: "No. Display, installation, maintenance and platform are part of the R$ 499 per display monthly fee." },
      { pergunta: "Who sells the slot to the brand?", resposta: "The chain sells its own space and keeps the revenue. Códice provides the rate card, the calendar and the proof of execution, and supports the conversation when asked." },
      { pergunta: "Does the sensor identify people?", resposta: "No. The count is aggregated, with no recognition camera and no shopper identification. The system reports passage and approximate dwell." },
      { pergunta: "What if the display breaks?", resposta: "Maintenance and repairs are in the monthly fee. The display reports lost connection and the incident becomes a task with a deadline." },
      { pergunta: "Can we start with a few stores?", resposta: "Yes. The contract is per display, so the chain starts in one region, measures the result and expands afterwards." },
      { pergunta: "How long until it pays off?", resposta: "One slot at R$ 1,500 covers three months of the Essencial plan. The simulator above shows your chain's profit over twelve months." },
    ],
  },
  conversao: {
    chapeu: "Talk to us",
    titulo: "Get the proposal with your chain's numbers",
    lead: "We reply within the same business day.",
    campos: { nome: "Name", empresa: "Chain", email: "Email", lojas: "Number of stores", mensagem: "Message" },
    enviar: "I want the proposal",
    enviando: "Preparing",
    sucesso: "Ready to send",
    sucessoDetalhe: "We opened your email with the message written. If nothing opened, write to",
    erro: "Check the highlighted fields",
    whatsapp: "Talk on WhatsApp",
    email: "Write an email",
    consentimento: "We use your data only to reply to this message.",
  },
  rodape: {
    frase: "Smart displays for serious results.",
    navegacao: "Navigation",
    contato: "Contact",
    privacidade: "Privacy policy",
    creditos: "Manufacturing by NeoBand. Trade and technology by 75 LAB.",
    direitos: "All rights reserved.",
  },
  privacidade: {
    titulo: "Privacy policy",
    atualizado: "Updated September 2026",
    blocos: [
      { titulo: "What this site collects", texto: "This site is static and uses no tracking cookies, advertising pixels or third party analytics." },
      { titulo: "The simulator", texto: "The numbers you type stay in your browser and are only sent if you choose to email the simulation." },
      { titulo: "The form", texto: "The form composes the message in your own email client. The data only leaves your device when you confirm the send." },
      { titulo: "What we use it for", texto: "Name, chain, email and message are used only to reply and prepare the proposal." },
      { titulo: "Data in the operation", texto: "Display sensors count traffic in aggregate, with no facial recognition and no shopper identification." },
      { titulo: "Your rights", texto: "You may request access, correction or deletion of the data you sent, under the Brazilian General Data Protection Law." },
    ],
    voltar: "Back to the site",
  },
  erro404: {
    titulo: "This page left the map",
    texto: "The address you opened no longer exists or never did.",
    voltar: "Back to the start",
  },
};
