import type { Conteudo } from "./tipos";

/* English. Mirrors src/conteudo/pt.ts. */
export const en: Conteudo = {
  meta: {
    titulo: "Códice · Your store is already a media channel",
    descricao:
      "Códice rents smart displays so your retail chain can sell space to brands. Display, maintenance and platform in one subscription of R$ 499 per display per month.",
    palavras: "retail media, in store display, display rental, shopper marketing, trade marketing, weekly slot",
    ogAlt: "Códice display installed in a supermarket",
  },
  nav: {
    links: [
      { id: "mudou", rotulo: "What changed" },
      { id: "como", rotulo: "How it works" },
      { id: "plataforma", rotulo: "Platform" },
      { id: "displays", rotulo: "Displays" },
      { id: "contas", rotulo: "The numbers" },
      { id: "simulador", rotulo: "Simulator" },
    ],
    cta: "Talk to Códice",
    abrirMenu: "Open menu",
    fecharMenu: "Close menu",
    idioma: "Language",
    irParaConteudo: "Skip to content",
  },
  abertura: { palavra: "Smart displays for serious results", pular: "Skip intro" },
  heroi: {
    chapeu: "Smart displays · Retail 2026",
    titulo: ["Your store is", "a media channel", "already"],
    lead:
      "Códice rents the display, keeps it running and provides the platform. Your chain sells the exposure week to brands. No furniture to buy, no capital tied up, no new team.",
    ctaPrimario: "Simulate my chain",
    ctaSecundario: "See the platform",
    selos: [
      { valor: "R$ 499", rotulo: "per display, per month" },
      { valor: "1 slot", rotulo: "= 1 week of 1 display" },
      { valor: "3 months", rotulo: "of rent paid by a single slot" },
      { valor: "0", rotulo: "capital tied up" },
    ],
    rolar: "Scroll to understand",
    legendaFoto: "Códice display installed in a supermarket",
  },
  mudou: {
    chapeu: "What changed",
    titulo: "Media budget moved into the aisle. Stores have not learned to charge for it.",
    lead:
      "Brands already treat the point of sale as a media channel and set budget aside for it every year. Whoever owns the store still hands over the best space in a shelf agreement, with no rate card and no revenue.",
    investimento: {
      valor: 48,
      prefixo: "R$ ",
      sufixo: "bn",
      separador: ".",
      rotulo: "invested in retail media in Brazil in 2025",
      fonte: "Source: IAB Brasil and Propmark, Digital Adspend 2026.",
    },
    crescimento: { valor: 37, sufixo: "%", rotulo: "growth per year" },
    canais: [
      { nome: "Broadcast TV", nota: "Wide reach, far from the purchase" },
      { nome: "Online display", nota: "Cheap, crowded and ignored" },
      { nome: "Out of home", nota: "Impact without measured conversion" },
      { nome: "Your store", nota: "The shopper with the cart in hand" },
    ],
    calculadora: {
      titulo: "What your chain leaves on the table",
      lojas: "Stores in the chain",
      displays: "Displays per store",
      cota: "Slot price",
      ocupacao: "Calendar sold per year",
      resultado: "Left on the table",
      porAno: "per year, every year",
      nota: "1 slot = 1 week of 1 display. The figure already deducts R$ 499 per display per month.",
    },
  },
  comoFunciona: {
    chapeu: "How it works",
    titulo: "Códice installs and maintains. Your chain sells the week.",
    lead:
      "Three moves, one contract. The chain buys no furniture, hires no maintenance and builds no media team to start earning from its own space.",
    passos: [
      {
        n: "01",
        titulo: "Códice installs the display",
        texto: "Design, production, in store assembly and staff training. The chain spends no capital to begin.",
        foto: "/fotos/foto-instalacao.jpg",
        alt: "Technical team installing the display in the store",
      },
      {
        n: "02",
        titulo: "The chain sells the week to brands",
        texto: "Brands buy the weekly slot with the creative included. Rate card, calendar and booking live in the platform.",
        foto: "/fotos/foto-ilha-supermercado.jpg",
        alt: "Códice display carrying a brand campaign in a supermarket",
      },
      {
        n: "03",
        titulo: "Códice maintains and measures",
        texto: "Scheduled maintenance, creative swaps and a report with proof of execution so the brand buys again.",
        foto: "/fotos/foto-monitoramento.jpg",
        alt: "Monitoring centre following the operation",
      },
    ],
    destaque: { valor: "R$ 499", rotulo: "per display, per month", nota: "Installation, maintenance and platform in the same subscription." },
    regra: "1 slot = 1 week of 1 display",
  },
  plataforma: {
    chapeu: "The platform",
    titulo: "Everything happening in the store, in one platform.",
    lead: "The same screen serves the chain, the brand and the field team. Click a screen to enlarge, or use the arrow keys.",
    telas: [
      { arquivo: "sis-painel", nome: "Dashboard", texto: "Occupancy, revenue and deadlines for the week on one screen." },
      { arquivo: "sis-inventario", nome: "Media inventory", texto: "Every display becomes weekly slots, with price and status." },
      { arquivo: "sis-campanhas", nome: "Campaigns", texto: "From the booking to the run, with the creative approved before it goes live." },
      { arquivo: "sis-sensores", nome: "Store sensors", texto: "Passage and dwell measured at the display, store by store." },
      { arquivo: "sis-mapa", nome: "Fleet map", texto: "Every store and every display on the map, with equipment health." },
      { arquivo: "sis-excecoes", nome: "Exceptions", texto: "Anything off plan becomes a task with a deadline and an owner." },
      { arquivo: "sis-campo", nome: "Field mode", texto: "Installation and inspection from the phone, with QR scan and photo." },
    ],
    ampliar: "View full screen",
    fechar: "Close",
    anterior: "Previous screen",
    proxima: "Next screen",
    aviso: "Real screens from the system, in demo mode with fictional data.",
    entrar: "Sign in to the platform",
  },
  displays: {
    chapeu: "The product",
    titulo: "Six formats. Spin and see each one.",
    lead:
      "Every display is modular and made in Brazil. The creative is swappable, so the same structure serves today's brand and the one three weeks from now.",
    instrucao: "Drag to spin",
    formatos: [
      { id: "essencial", rotulo: "End cap", nome: "Gondola end cap", texto: "The most contested spot in the store, with a header and side banners.", uso: "Brand campaign and promotions", medidas: "202 × 104 × 55 cm" },
      { id: "ilha", rotulo: "Island", nome: "Double sided island", texto: "Two selling faces in one display, for wide aisles.", uso: "Owning a category", medidas: "190 × 120 × 96 cm" },
      { id: "painel", rotulo: "Panel", nome: "Accessory panel", texto: "Slatted panel with hooks for small, high value items.", uso: "Accessories and convenience", medidas: "195 × 122 × 42 cm" },
      { id: "vitrine", rotulo: "Cabinet", nome: "Premium cabinet", texto: "Glass doors that protect the product and raise the slot value.", uso: "Launches and premium", medidas: "192 × 122 × 54 cm" },
      { id: "categoria", rotulo: "Category", nome: "Category stand", texto: "Shelves with acrylic fronts and a brand band at the base.", uso: "Cosmetics and personal care", medidas: "200 × 100 × 46 cm" },
      { id: "multiuso", rotulo: "Multi use", nome: "Multi use with drawers", texto: "Shelves on top and backup stock underneath.", uso: "High turnover and volume", medidas: "195 × 74 × 52 cm" },
    ],
    rotulos: { uso: "Best for", medidas: "Dimensions", ver3d: "3D model, spin with your finger or the mouse" },
  },
  pacotes: {
    chapeu: "Packages",
    titulo: "Three levels of technology in the same display.",
    lead:
      "The structure is the same. What changes is how much the display can measure and prove, and that changes how much the chain can charge per slot.",
    porMes: "per display, per month",
    itens: [
      { id: "essencial", nome: "Essencial", preco: 499, selo: "Best to start", quem: "To start selling space right away, with low complexity.", recursos: ["Modular display", "Swappable creative", "Asset QR code", "Maintenance included"] },
      { id: "sense", nome: "Sense", preco: 849, selo: "Most chosen", quem: "For higher traffic spots, with proof that the audience walked by.", recursos: ["Everything in Essencial", "Proximity sensor", "Connection alerts", "Execution dashboard"] },
      { id: "media", nome: "Media", preco: 1290, selo: "Highest value per slot", quem: "For launches and premium campaigns, with video inside the store.", recursos: ["Everything in Sense", "Screen and player", "Remote content", "Proof of play"] },
    ],
    nota: "Prices per display per month, with installation, maintenance and platform included.",
  },
  tecnologia: {
    chapeu: "Built in technology",
    titulo: "A sensor only goes in when it drives a decision.",
    lead:
      "The inner layer already ships with the packages. The outer layer comes per project, when the category justifies it. Nothing here identifies a person.",
    instrucao: "Click a module to read",
    camadas: { interna: "Inner layer", externa: "Outer layer" },
    modulos: [
      { camada: "interna", plano: "Essencial", titulo: "Asset and shopper QR", texto: "One code controls asset, store, campaign and team check in. The other takes the shopper to a coupon, a survey or the brand page.", decide: "Proof of installation and interest" },
      { camada: "interna", plano: "Essencial", titulo: "Visit geolocation", texto: "Records the coordinate at team check in, with the accuracy reported by the device. The QR alone tracks nobody.", decide: "Proof of route and visit" },
      { camada: "interna", plano: "Sense", titulo: "Proximity sensor", texto: "Measures passages in the display zone and approximate dwell. Used to price position, not to promise audience.", decide: "Slot price by position" },
      { camada: "interna", plano: "Sense", titulo: "Connectivity and alerts", texto: "The display reports when it drops, when the campaign changes and when something needs a technician.", decide: "Uptime and maintenance route" },
      { camada: "interna", plano: "Media", titulo: "Screen and remote content", texto: "Playlist by day, store and category, changed with no site visit, logging file, time and failures.", decide: "Premium sales and proof of play" },
      { camada: "interna", plano: "Media", titulo: "Smart lighting", texto: "LED that highlights the spot with low consumption and reports its own working state.", decide: "Standout and asset health" },
      { camada: "externa", plano: "Project", titulo: "Weight sensing shelf", texto: "Weight variation indicates pick up, restock and possible out of stock. A pick up is not a confirmed sale.", decide: "Out of stock and restock" },
      { camada: "externa", plano: "Project", titulo: "Sell out integration", texto: "Crosses the campaign with aggregated sales by SKU, store and date to assess commercial impact rigorously.", decide: "Real campaign impact" },
      { camada: "externa", plano: "Project", titulo: "Computer vision", texto: "Checks planogram and availability from product and shelf images. Never facial recognition.", decide: "Execution compliance" },
      { camada: "externa", plano: "Project", titulo: "Temperature", texto: "For chilled and sensitive categories, with history and deviation alerts.", decide: "Category safety" },
    ],
    rotulos: { entra: "Included in", decide: "Drives" },
  },
  contas: {
    chapeu: "The numbers",
    titulo: "Buying demands capital before any sale. Subscribing costs R$ 499 a month.",
    lead: "The comparison below uses the business plan assumptions, in the first month of operation, per display.",
    comprar: {
      titulo: "Buying on your own",
      valor: 3620,
      unidade: "per display, in month 1",
      linhas: ["Display R$ 3,200", "Installation R$ 350", "Maintenance and operation R$ 70"],
      contras: ["Capital parked before the first sale", "Maintenance and repairs on the chain", "Technology ageing on the balance sheet"],
    },
    assinar: {
      titulo: "Subscribing to Códice",
      valor: 499,
      unidade: "per display, per month",
      selo: "86% less in month 1",
      linhas: ["All inclusive subscription", "No capital tied up", "Installation and maintenance included", "Technology that evolves by layer"],
    },
    cota: {
      titulo: "One slot sold pays three months of rent",
      texto: "1 slot = 1 week of 1 display, sold to the brand at R$ 1,500 in the plan reference.",
      meses: "Month",
    },
    fiscal: {
      titulo: "As a subscription, the spend becomes an expense that lowers tax",
      lead: "Pick your chain's tax regime and see the effective cost of the monthly fee.",
      regimes: [
        { nome: "Simples or Presumido", nota: "No effect on tax", custo: 499, volta: 0 },
        { nome: "Lucro Real · 24%", nota: "IRPJ 15% plus CSLL 9%", custo: 379, volta: 120 },
        { nome: "Lucro Real · 34%", nota: "With the IRPJ surcharge", custo: 329, volta: 170 },
      ],
      rotulos: { custoEfetivo: "Effective cost per month", volta: "returns as tax", semEfeito: "No effect on tax" },
      ressalva:
        "Applies to the Lucro Real regime, when the expense is necessary, usual and documented. When bought, the display becomes a fixed asset and depreciates about 10% a year. Confirm with your accountant.",
    },
  },
  industria: {
    chapeu: "For brands",
    titulo: "An owned display costs a lot and nobody maintains it. With Códice, the brand buys only the week.",
    lead: "The same structure that generates revenue for the chain solves six old pains for whoever invests at the point of sale.",
    linhas: [
      { dor: "Expensive display", dorTexto: "Produced per campaign and discarded afterwards", solucao: "Buy only the week", solucaoTexto: "Weekly slot with the creative included" },
      { dor: "No maintenance", dorTexto: "Broken, dirty and off brand standard", solucao: "Scheduled maintenance", solucaoTexto: "Códice keeps the spot in order" },
      { dor: "Store by store logistics", dorTexto: "Produce, ship and assemble at every store", solucao: "Display already installed", solucaoTexto: "The brand only sends the artwork" },
      { dor: "Space negotiated case by case", dorTexto: "No rate card, no calendar, no standard", solucao: "Calendar with a rate card", solucaoTexto: "Booking by week, position and store" },
      { dor: "No proof of execution", dorTexto: "No idea whether it was assembled or where it ended up", solucao: "Proof with photo and QR", solucaoTexto: "Evidence of installation per store" },
      { dor: "No result data", dorTexto: "Investing without measuring the return", solucao: "Sensors and reporting", solucaoTexto: "Traffic and play per campaign" },
    ],
    etapas: {
      proprio: { titulo: "Owned display: 5 stages on the brand", itens: ["Design", "Production", "Freight", "Assembly", "Maintenance"] },
      codice: { titulo: "Códice slot: 3 stages, display ready", itens: ["Booking", "Artwork", "Live"] },
    },
  },
  simulador: {
    chapeu: "Simulator",
    titulo: "Put your chain in and see when the profit arrives.",
    lead: "The numbers move as you move. Nothing here is sent anywhere.",
    campos: { pacote: "Package", displays: "Displays per store", lojas: "Stores in the chain", cota: "Slot price", ocupacao: "Calendar sold", periodo: "Contract period" },
    periodos: [
      { rotulo: "1 month", meses: 1 },
      { rotulo: "6 months", meses: 6 },
      { rotulo: "12 months", meses: 12 },
    ],
    saidas: { receita: "Revenue from slots", aluguel: "Códice rent", lucro: "Potential profit" },
    grafico: "Accumulated profit month by month",
    nota: "The brand buys the display week with the creative included. Figures before tax. Average month of 4.3 weeks.",
    enviar: "Send this simulation",
  },
  grupo: {
    chapeu: "Who delivers",
    titulo: "Códice is born inside a group that already makes retail happen.",
    lead: "The factory produces, the trade team designs and measures, and Códice joins both ends in one contract per display.",
    empresas: [
      {
        nome: "NeoBand",
        papel: "The factory",
        texto: "Manufactures every Códice display, with four decades of point of sale furniture.",
        numeros: [
          { valor: "40+", rotulo: "years manufacturing" },
          { valor: "100%", rotulo: "produced in Brazil" },
          { valor: "FSC", rotulo: "certified materials" },
          { valor: "2025", rotulo: "Supplier of the Year" },
        ],
      },
      {
        nome: "75 LAB",
        papel: "Trade and technology",
        texto: "Designs the in store experience, builds the platform and measures the result at the point of sale.",
        numeros: [
          { valor: "15+", rotulo: "years in trade marketing" },
          { valor: "15,000+", rotulo: "stores activated" },
          { valor: "95%", rotulo: "projects approved" },
          { valor: "84", rotulo: "cases delivered" },
        ],
      },
    ],
    ressalva: "The figures above belong to the group companies. Códice is the new operation that joins the two.",
  },
  honestidade: {
    chapeu: "Honest data",
    titulo: "What Códice refuses to claim.",
    lead:
      "Retail media is full of inflated numbers. Every metric here says what it measured and nothing beyond it. That is what holds the conversation with the brand at renewal.",
    itens: [
      { afirma: "Passages measured by the sensor", naoAfirma: "Not unique people" },
      { afirma: "Dwell time near the display", naoAfirma: "Not visual attention" },
      { afirma: "Position at the moment of the QR scan", naoAfirma: "Not continuous tracking" },
      { afirma: "Product picked from the shelf", naoAfirma: "Not a sale" },
      { afirma: "Proof of play for the creative", naoAfirma: "Not audience" },
      { afirma: "Aggregated traffic count", naoAfirma: "No facial recognition" },
    ],
  },
  faq: {
    chapeu: "Frequently asked",
    titulo: "What people ask before signing.",
    itens: [
      { pergunta: "Does my chain need to buy anything to start?", resposta: "No. Display, installation, maintenance and platform are part of the R$ 499 per display per month subscription. No capital leaves the chain before the first slot is sold." },
      { pergunta: "Who sells the slot to the brand?", resposta: "The chain sells its own space and keeps the revenue. The platform provides the rate card, the calendar and the proof of execution for the conversation with the brand. Códice also supports commercially when the chain asks." },
      { pergunta: "Does the sensor identify people walking by?", resposta: "No. The count is aggregated, with no facial recognition and no shopper identification. The system reports passage and approximate dwell, and repeats that limit on every screen where the number appears." },
      { pergunta: "What if the display breaks or the campaign changes?", resposta: "Maintenance and creative swaps are in the subscription. The display itself reports when the connection drops, and the incident becomes a task with a deadline in the platform." },
      { pergunta: "Can we start with a few stores?", resposta: "Yes. The contract is per display, so the chain can start with one region or a group of stores, measure the result and expand afterwards." },
      { pergunta: "How long until the display pays for itself?", resposta: "In the plan reference, one slot at R$ 1,500 covers three months of the Essencial package. The simulator on this page shows the month when your chain's accumulated profit turns positive." },
    ],
  },
  conversao: {
    chapeu: "Next step",
    titulo: "Bring Códice to your chain.",
    lead: "A forty minute conversation with your store count on the table: formats, slot rate card and the month the operation starts turning a profit.",
    campos: { nome: "Name", empresa: "Chain or company", email: "Email", lojas: "Number of stores", mensagem: "Tell us your scenario" },
    ajuda: { nome: "What should we call you", email: "Used only to reply", mensagem: "The more specific, the better we prepare" },
    enviar: "I want a proposal",
    enviando: "Preparing",
    sucesso: "Ready to send",
    sucessoDetalhe: "We opened your email client with the message written. Just confirm the send. If nothing opened, write to",
    erro: "Check the highlighted fields",
    alternativaTitulo: "Prefer another route?",
    alternativaWhatsapp: "Talk on WhatsApp",
    alternativaEmail: "Write an email",
    consentimento: "By sending, you agree that Códice uses this data only to reply to your message.",
  },
  rodape: {
    frase: "Smart displays for serious results.",
    navegacao: "Navigation",
    contato: "Contact",
    legal: "Legal",
    privacidade: "Privacy policy",
    creditos: "Manufacturing by NeoBand. Trade and technology by 75 LAB.",
    direitos: "All rights reserved.",
  },
  privacidade: {
    titulo: "Privacy policy",
    atualizado: "Updated September 2026",
    blocos: [
      { titulo: "What this site collects", texto: "This site is static and uses no tracking cookies, advertising pixels or third party analytics. Nothing you read or simulate here leaves your browser." },
      { titulo: "The simulator", texto: "The numbers you type into the simulator stay in your browser memory only. None of them reach Códice unless you choose to send the simulation by email." },
      { titulo: "The contact form", texto: "The form composes a message in your own email client. The data only leaves your device when you confirm the send." },
      { titulo: "What we use it for", texto: "Name, company, email and message are used only to reply and prepare the proposal. We do not sell or share this data with third parties." },
      { titulo: "Data in the operation", texto: "Display sensors count traffic in aggregate, with no facial recognition and no shopper identification. No person is identified at any stage." },
      { titulo: "Your rights", texto: "You may request access, correction or deletion of the data you sent, under the Brazilian General Data Protection Law. Requests are handled through the same contact address." },
    ],
    voltar: "Back to the site",
  },
  erro404: {
    titulo: "This page left the map.",
    texto: "The address you opened no longer exists or never did. It happens even to a well managed display.",
    voltar: "Back to the start",
  },
};
