import type { Conteudo } from "./tipos";

/* Español. Refleja src/conteudo/pt.ts. */
export const es: Conteudo = {
  meta: {
    titulo: "Códice · Tu tienda ya es un medio",
    descricao:
      "Códice alquila displays inteligentes para que tu cadena venda espacio a las marcas. Display, mantenimiento y plataforma en una suscripción de R$ 499 por display por mes.",
    palavras: "retail media, display de punto de venta, alquiler de display, trade marketing, cupo semanal",
    ogAlt: "Display Códice instalado en un supermercado",
  },
  nav: {
    links: [
      { id: "mudou", rotulo: "Qué cambió" },
      { id: "como", rotulo: "Cómo funciona" },
      { id: "plataforma", rotulo: "Plataforma" },
      { id: "displays", rotulo: "Displays" },
      { id: "contas", rotulo: "La cuenta" },
      { id: "simulador", rotulo: "Simulador" },
    ],
    cta: "Hablar con Códice",
    abrirMenu: "Abrir menú",
    fecharMenu: "Cerrar menú",
    idioma: "Idioma",
    irParaConteudo: "Ir al contenido",
  },
  abertura: { palavra: "Displays inteligentes para grandes resultados", pular: "Saltar apertura" },
  heroi: {
    chapeu: "Displays inteligentes · Retail 2026",
    titulo: ["Tu tienda ya es", "un medio", "de comunicación"],
    lead:
      "Códice alquila el display, mantiene el punto y entrega la plataforma. Tu cadena vende la semana de exposición a las marcas. Sin comprar mueble, sin capital inmovilizado, sin equipo nuevo.",
    ctaPrimario: "Simular mi cadena",
    ctaSecundario: "Ver la plataforma",
    selos: [
      { valor: "R$ 499", rotulo: "por display, por mes" },
      { valor: "1 cupo", rotulo: "= 1 semana de 1 display" },
      { valor: "3 meses", rotulo: "de alquiler pagados por un cupo" },
      { valor: "0", rotulo: "capital inmovilizado" },
    ],
    rolar: "Desplázate para entender",
    legendaFoto: "Display Códice instalado en un supermercado",
  },
  mudou: {
    chapeu: "Qué cambió",
    titulo: "El presupuesto de medios bajó al pasillo. La tienda todavía no aprendió a cobrarlo.",
    lead:
      "La industria ya trata el punto de venta como canal de medios y reserva presupuesto cada año. Quien tiene la tienda sigue cediendo el mejor espacio por acuerdo de góndola, sin tarifa y sin ingreso.",
    investimento: {
      valor: 48,
      prefixo: "R$ ",
      sufixo: " mil M",
      separador: ",",
      rotulo: "invertidos en retail media en Brasil en 2025",
      fonte: "Fuente: IAB Brasil y Propmark, Digital Adspend 2026.",
    },
    crescimento: { valor: 37, sufixo: "%", rotulo: "de crecimiento por año" },
    canais: [
      { nome: "TV abierta", nota: "Alcance amplio, lejos de la compra" },
      { nome: "Display online", nota: "Barato, disputado e ignorado" },
      { nome: "Vía pública", nota: "Impacto sin conversión medida" },
      { nome: "Tu tienda", nota: "El shopper con el carrito en la mano" },
    ],
    calculadora: {
      titulo: "Cuánto deja tu cadena sobre la mesa",
      lojas: "Tiendas de la cadena",
      displays: "Displays por tienda",
      cota: "Precio del cupo",
      ocupacao: "Agenda vendida al año",
      resultado: "Queda sobre la mesa",
      porAno: "por año, todos los años",
      nota: "1 cupo = 1 semana de 1 display. El valor ya descuenta R$ 499 por display por mes.",
    },
  },
  comoFunciona: {
    chapeu: "Cómo funciona",
    titulo: "Códice instala y mantiene. Tu cadena vende la semana.",
    lead:
      "Tres movimientos, un solo contrato. La cadena no compra mueble, no contrata mantenimiento y no arma equipo de medios para empezar a facturar con su propio espacio.",
    passos: [
      {
        n: "01",
        titulo: "Códice instala el display",
        texto: "Proyecto, producción, montaje en tienda y capacitación del equipo. La cadena no desembolsa capital para empezar.",
        foto: "/fotos/foto-instalacao.jpg",
        alt: "Equipo técnico instalando el display en la tienda",
      },
      {
        n: "02",
        titulo: "La cadena vende la semana a las marcas",
        texto: "La industria compra el cupo semanal con la comunicación incluida. Tarifa, calendario y reserva viven en la plataforma.",
        foto: "/fotos/foto-ilha-supermercado.jpg",
        alt: "Display Códice con la campaña de una marca en un supermercado",
      },
      {
        n: "03",
        titulo: "Códice mantiene y mide",
        texto: "Mantenimiento programado, cambio de comunicación e informe con prueba de ejecución para que la marca compre de nuevo.",
        foto: "/fotos/foto-monitoramento.jpg",
        alt: "Central de monitoreo siguiendo la operación",
      },
    ],
    destaque: { valor: "R$ 499", rotulo: "por display, por mes", nota: "Instalación, mantenimiento y plataforma en la misma suscripción." },
    regra: "1 cupo = 1 semana de 1 display",
  },
  plataforma: {
    chapeu: "La plataforma",
    titulo: "Todo lo que pasa en la tienda, en una sola plataforma.",
    lead: "La misma pantalla sirve a la cadena, a la marca y al equipo de campo. Haz clic en una pantalla para ampliar, o usa las flechas del teclado.",
    telas: [
      { arquivo: "sis-painel", nome: "Panel", texto: "Ocupación, ingreso y plazos de la semana en una pantalla." },
      { arquivo: "sis-inventario", nome: "Inventario de medios", texto: "Cada display se convierte en cupos semanales, con precio y estado." },
      { arquivo: "sis-campanhas", nome: "Campañas", texto: "De la reserva a la salida al aire, con la pieza aprobada antes de subir." },
      { arquivo: "sis-sensores", nome: "Sensores de tienda", texto: "Paso y permanencia medidos en el punto, tienda por tienda." },
      { arquivo: "sis-mapa", nome: "Mapa de la flota", texto: "Cada tienda y cada display en el mapa, con la salud del equipo." },
      { arquivo: "sis-excecoes", nome: "Excepciones", texto: "Lo que se sale del plan se vuelve tarea con plazo y responsable." },
      { arquivo: "sis-campo", nome: "Modo campo", texto: "Instalación e inspección desde el celular, con lectura de QR y foto." },
    ],
    ampliar: "Ver en pantalla completa",
    fechar: "Cerrar",
    anterior: "Pantalla anterior",
    proxima: "Pantalla siguiente",
    aviso: "Pantallas reales del sistema, en modo demostración con datos ficticios.",
    entrar: "Entrar a la plataforma",
  },
  displays: {
    chapeu: "El producto",
    titulo: "Seis formatos. Gíralos y míralos.",
    lead:
      "Todo display es modular y fabricado en Brasil. La comunicación es intercambiable, así que la misma estructura sirve a la marca de hoy y a la de dentro de tres semanas.",
    instrucao: "Arrastra para girar",
    formatos: [
      { id: "essencial", rotulo: "Cabecera", nome: "Cabecera de góndola", texto: "El punto más disputado de la tienda, con copete y banners laterales.", uso: "Campaña de marca y oferta", medidas: "202 × 104 × 55 cm" },
      { id: "ilha", rotulo: "Isla", nome: "Isla de doble cara", texto: "Dos frentes de venta en el mismo display, para pasillo ancho.", uso: "Dominar una categoría", medidas: "190 × 120 × 96 cm" },
      { id: "painel", rotulo: "Panel", nome: "Panel de accesorios", texto: "Panel ranurado con ganchos para artículos pequeños de alto valor.", uso: "Accesorios y conveniencia", medidas: "195 × 122 × 42 cm" },
      { id: "vitrine", rotulo: "Vitrina", nome: "Vitrina premium", texto: "Puertas de vidrio que protegen el producto y valorizan el cupo.", uso: "Lanzamiento y premium", medidas: "192 × 122 × 54 cm" },
      { id: "categoria", rotulo: "Categoría", nome: "Exhibidor de categoría", texto: "Estantes con acrílico y franja de marca en la base.", uso: "Cosmética e higiene", medidas: "200 × 100 × 46 cm" },
      { id: "multiuso", rotulo: "Multiuso", nome: "Multiuso con cajones", texto: "Estantes arriba y stock de apoyo abajo.", uso: "Alta rotación y volumen", medidas: "195 × 74 × 52 cm" },
    ],
    rotulos: { uso: "Indicado para", medidas: "Medidas", ver3d: "Modelo 3D, gíralo con el dedo o con el mouse" },
  },
  pacotes: {
    chapeu: "Paquetes",
    titulo: "Tres niveles de tecnología en el mismo display.",
    lead:
      "La estructura es la misma. Lo que cambia es cuánto puede medir y probar el display, y eso cambia cuánto puede cobrar la cadena por el cupo.",
    porMes: "por display, por mes",
    itens: [
      { id: "essencial", nome: "Essencial", preco: 499, selo: "Ideal para empezar", quem: "Para empezar a vender espacio ya, con baja complejidad.", recursos: ["Display modular", "Comunicación intercambiable", "QR patrimonial", "Mantenimiento incluido"] },
      { id: "sense", nome: "Sense", preco: 849, selo: "El más elegido", quem: "Para puntos de mayor flujo, con prueba de que el público pasó.", recursos: ["Todo lo del Essencial", "Sensor de proximidad", "Alertas de conexión", "Panel de ejecución"] },
      { id: "media", nome: "Media", preco: 1290, selo: "Mayor valor por cupo", quem: "Para lanzamientos y campañas premium, con video dentro de la tienda.", recursos: ["Todo lo del Sense", "Pantalla y player", "Contenido remoto", "Prueba de emisión"] },
    ],
    nota: "Valores por display por mes, con instalación, mantenimiento y plataforma incluidos.",
  },
  tecnologia: {
    chapeu: "Tecnología embarcada",
    titulo: "El sensor entra solo cuando genera una decisión.",
    lead:
      "La capa interna ya viene en los paquetes. La capa externa entra por proyecto, cuando la categoría lo justifica. Nada aquí identifica a una persona.",
    instrucao: "Haz clic en un módulo para leer",
    camadas: { interna: "Capa interna", externa: "Capa externa" },
    modulos: [
      { camada: "interna", plano: "Essencial", titulo: "QR patrimonial y del shopper", texto: "Un código controla activo, tienda, campaña y check in del equipo. El otro lleva al shopper a un cupón, una encuesta o la página de la marca.", decide: "Prueba de instalación e interés" },
      { camada: "interna", plano: "Essencial", titulo: "Geolocalización de visita", texto: "Registra la coordenada en el check in del equipo, con la precisión informada por el aparato. El QR solo no rastrea a nadie.", decide: "Comprobación de ruta y visita" },
      { camada: "interna", plano: "Sense", titulo: "Sensor de proximidad", texto: "Mide pasos en la zona del display y permanencia aproximada. Sirve para tarifar posición, no para prometer audiencia.", decide: "Precio del cupo por posición" },
      { camada: "interna", plano: "Sense", titulo: "Conectividad y alertas", texto: "El display avisa cuando se cae, cuando cambia la campaña y cuando algo necesita visita técnica.", decide: "Uptime y ruta de mantenimiento" },
      { camada: "interna", plano: "Media", titulo: "Pantalla y contenido remoto", texto: "Playlist por día, tienda y categoría, cambiada sin visita técnica, con registro de archivo, horario y fallas.", decide: "Venta premium y prueba de emisión" },
      { camada: "interna", plano: "Media", titulo: "Iluminación inteligente", texto: "LED que destaca el punto con bajo consumo y reporta su propio estado de funcionamiento.", decide: "Destaque y salud del activo" },
      { camada: "externa", plano: "Proyecto", titulo: "Estante con peso", texto: "La variación de peso indica retiro, reposición y posible quiebre. Retirar no es venta confirmada.", decide: "Quiebre y reposición" },
      { camada: "externa", plano: "Proyecto", titulo: "Integración de sell out", texto: "Cruza la campaña con la venta agregada por SKU, tienda y fecha para evaluar el impacto comercial con rigor.", decide: "Impacto real de la campaña" },
      { camada: "externa", plano: "Proyecto", titulo: "Visión computacional", texto: "Verifica planograma y disponibilidad por imagen de producto y estante. Nunca reconocimiento facial.", decide: "Conformidad de ejecución" },
      { camada: "externa", plano: "Proyecto", titulo: "Temperatura", texto: "Para categorías refrigeradas y sensibles, con histórico y alerta de desvío.", decide: "Seguridad de la categoría" },
    ],
    rotulos: { entra: "Entra en el plan", decide: "Decide" },
  },
  contas: {
    chapeu: "La cuenta",
    titulo: "Comprar exige capital antes de vender. Suscribirse cuesta R$ 499 por mes.",
    lead: "La comparación usa las premisas del plan de negocio, en el primer mes de operación, por display.",
    comprar: {
      titulo: "Comprar por cuenta propia",
      valor: 3620,
      unidade: "por display, en el 1er mes",
      linhas: ["Display R$ 3.200", "Instalación R$ 350", "Mantenimiento y operación R$ 70"],
      contras: ["Capital parado antes de la primera venta", "Mantenimiento y reparaciones a cargo de la cadena", "Tecnología que envejece en el balance"],
    },
    assinar: {
      titulo: "Suscribirse a Códice",
      valor: 499,
      unidade: "por display, por mes",
      selo: "86% menos en el 1er mes",
      linhas: ["Suscripción con todo incluido", "Ningún capital inmovilizado", "Instalación y mantenimiento incluidos", "Tecnología que evoluciona por capa"],
    },
    cota: {
      titulo: "Un cupo vendido paga tres meses de alquiler",
      texto: "1 cupo = 1 semana de 1 display, vendida a la marca a R$ 1.500 en la referencia del plan.",
      meses: "Mes",
    },
    fiscal: {
      titulo: "En la suscripción, el gasto es un egreso que reduce impuesto",
      lead: "Elige el régimen de tu cadena y mira el costo efectivo de la mensualidad.",
      regimes: [
        { nome: "Simples o Presumido", nota: "Sin efecto en el impuesto", custo: 499, volta: 0 },
        { nome: "Lucro Real · 24%", nota: "IRPJ 15% más CSLL 9%", custo: 379, volta: 120 },
        { nome: "Lucro Real · 34%", nota: "Con adicional de IRPJ", custo: 329, volta: 170 },
      ],
      rotulos: { custoEfetivo: "Costo efectivo por mes", volta: "vuelve en impuesto", semEfeito: "Sin efecto en el impuesto" },
      ressalva:
        "Vale para el régimen brasileño Lucro Real, cuando el gasto es necesario, usual y comprobado. Al comprar, el display se vuelve activo fijo y se deprecia cerca de 10% al año. Confirma con tu contabilidad.",
    },
  },
  industria: {
    chapeu: "Para la industria",
    titulo: "El display propio cuesta caro y nadie lo mantiene. Con Códice, la marca compra solo la semana.",
    lead: "La misma estructura que genera ingreso para la cadena resuelve seis dolores viejos de quien invierte en punto de venta.",
    linhas: [
      { dor: "Display caro", dorTexto: "Producido por campaña y descartado después", solucao: "Compra solo la semana", solucaoTexto: "Cupo semanal con la comunicación incluida" },
      { dor: "Sin mantenimiento", dorTexto: "Roto, sucio y fuera del estándar de marca", solucao: "Mantenimiento programado", solucaoTexto: "Códice mantiene el punto siempre en orden" },
      { dor: "Logística tienda por tienda", dorTexto: "Producir, enviar y montar en cada punto", solucao: "Display ya instalado", solucaoTexto: "La marca envía solo el arte" },
      { dor: "Espacio negociado caso por caso", dorTexto: "Sin tarifa, sin calendario, sin estándar", solucao: "Agenda con tarifa", solucaoTexto: "Reserva por semana, posición y tienda" },
      { dor: "Sin prueba de ejecución", dorTexto: "No sabe si lo montaron ni dónde quedó", solucao: "Prueba con foto y QR", solucaoTexto: "Evidencia de instalación por tienda" },
      { dor: "Sin dato de resultado", dorTexto: "Invierte sin medir el retorno", solucao: "Sensores e informe", solucaoTexto: "Flujo y emisión por campaña" },
    ],
    etapas: {
      proprio: { titulo: "Display propio: 5 etapas a cargo de la marca", itens: ["Proyecto", "Producción", "Flete", "Montaje", "Mantenimiento"] },
      codice: { titulo: "Cupo Códice: 3 etapas, display listo", itens: ["Reserva", "Arte", "Al aire"] },
    },
  },
  simulador: {
    chapeu: "Simulador",
    titulo: "Pon tu cadena y mira cuándo llega la ganancia.",
    lead: "Los números cambian mientras mueves los controles. Nada de esto se envía a ningún lado.",
    campos: { pacote: "Paquete", displays: "Displays por tienda", lojas: "Tiendas de la cadena", cota: "Precio del cupo", ocupacao: "Agenda vendida", periodo: "Período del contrato" },
    periodos: [
      { rotulo: "1 mes", meses: 1 },
      { rotulo: "6 meses", meses: 6 },
      { rotulo: "12 meses", meses: 12 },
    ],
    saidas: { receita: "Ingreso con cupos", aluguel: "Alquiler Códice", lucro: "Ganancia potencial" },
    grafico: "Ganancia acumulada mes a mes",
    nota: "La marca compra la semana del display, con la comunicación incluida. Valores antes de impuestos. Mes promedio de 4,3 semanas.",
    enviar: "Enviar esta simulación",
  },
  grupo: {
    chapeu: "Quién entrega",
    titulo: "Códice nace dentro de un grupo que ya hace que el retail suceda.",
    lead: "La fábrica produce, el equipo de trade diseña y mide, y Códice une las dos puntas en un contrato por display.",
    empresas: [
      {
        nome: "NeoBand",
        papel: "La fábrica",
        texto: "Fabrica cada display de Códice, con cuatro décadas de mobiliario de punto de venta.",
        numeros: [
          { valor: "40+", rotulo: "años de fabricación" },
          { valor: "100%", rotulo: "producción en Brasil" },
          { valor: "FSC", rotulo: "materiales certificados" },
          { valor: "2025", rotulo: "Proveedor del Año" },
        ],
      },
      {
        nome: "75 LAB",
        papel: "Trade y tecnología",
        texto: "Diseña la experiencia en tienda, construye la plataforma y mide el resultado en el punto de venta.",
        numeros: [
          { valor: "15+", rotulo: "años en trade marketing" },
          { valor: "15.000+", rotulo: "puntos activados" },
          { valor: "95%", rotulo: "proyectos aprobados" },
          { valor: "84", rotulo: "casos entregados" },
        ],
      },
    ],
    ressalva: "Los números de arriba son de las empresas del grupo. Códice es la operación nueva que une a las dos.",
  },
  honestidade: {
    chapeu: "Honestidad de los datos",
    titulo: "Lo que Códice se niega a afirmar.",
    lead:
      "El retail media está lleno de números inflados. Cada métrica aquí dice lo que midió y nada más. Eso es lo que sostiene la conversación con la marca en la renovación.",
    itens: [
      { afirma: "Pasos medidos por el sensor", naoAfirma: "No son personas únicas" },
      { afirma: "Permanencia cerca del display", naoAfirma: "No es atención visual" },
      { afirma: "Posición al momento de leer el QR", naoAfirma: "No es rastreo continuo" },
      { afirma: "Producto retirado del estante", naoAfirma: "No es una venta" },
      { afirma: "Prueba de emisión de la pieza", naoAfirma: "No es audiencia" },
      { afirma: "Conteo agregado de flujo", naoAfirma: "Sin reconocimiento facial" },
    ],
  },
  faq: {
    chapeu: "Preguntas frecuentes",
    titulo: "Lo que preguntan antes de cerrar.",
    itens: [
      { pergunta: "¿Mi cadena necesita comprar algo para empezar?", resposta: "No. El display, la instalación, el mantenimiento y la plataforma entran en la suscripción de R$ 499 por display por mes. No sale capital de la caja antes del primer cupo vendido." },
      { pergunta: "¿Quién vende el cupo a la industria?", resposta: "La cadena vende su propio espacio y se queda con el ingreso. La plataforma entrega la tarifa, el calendario y la prueba de ejecución para la conversación con la marca. Códice también apoya comercialmente cuando la cadena lo pide." },
      { pergunta: "¿El sensor identifica a las personas que pasan?", resposta: "No. El conteo es agregado, sin reconocimiento facial y sin identificar al shopper. El sistema informa paso y permanencia aproximada, y repite ese límite en cada pantalla donde aparece el número." },
      { pergunta: "¿Y si el display se rompe o cambia la campaña?", resposta: "Mantenimiento y cambio de comunicación están en la suscripción. El display avisa cuando cae la conexión, y la incidencia se vuelve tarea con plazo dentro de la plataforma." },
      { pergunta: "¿Se puede empezar con pocas tiendas?", resposta: "Sí. El contrato es por display, así que la cadena puede empezar por una plaza o un grupo de tiendas, medir el resultado y ampliar después." },
      { pergunta: "¿En cuánto tiempo se paga el display?", resposta: "En la referencia del plan, un cupo de R$ 1.500 cubre tres meses del paquete Essencial. El simulador de esta página muestra el mes en que la ganancia acumulada de tu cadena se vuelve positiva." },
    ],
  },
  conversao: {
    chapeu: "Próximo paso",
    titulo: "Lleva Códice a tu cadena.",
    lead: "Una conversación de cuarenta minutos con tu número de tiendas sobre la mesa: formatos, tarifa del cupo y el mes en que la operación empieza a dar ganancia.",
    campos: { nome: "Nombre", empresa: "Cadena o empresa", email: "Correo", lojas: "Número de tiendas", mensagem: "Cuéntanos tu escenario" },
    ajuda: { nome: "Cómo debemos llamarte", email: "Lo usamos solo para responder", mensagem: "Cuanto más específico, mejor preparamos la conversación" },
    enviar: "Quiero una propuesta",
    enviando: "Preparando",
    sucesso: "Listo para enviar",
    sucessoDetalhe: "Abrimos tu programa de correo con el mensaje escrito. Solo falta confirmar el envío. Si no se abrió nada, escribe a",
    erro: "Revisa los campos destacados",
    alternativaTitulo: "¿Prefieres otro camino?",
    alternativaWhatsapp: "Hablar por WhatsApp",
    alternativaEmail: "Escribir un correo",
    consentimento: "Al enviar, aceptas que Códice use estos datos solo para responder a tu contacto.",
  },
  rodape: {
    frase: "Displays inteligentes para grandes resultados.",
    navegacao: "Navegación",
    contato: "Contacto",
    legal: "Legal",
    privacidade: "Política de privacidad",
    creditos: "Fabricación NeoBand. Trade y tecnología 75 LAB.",
    direitos: "Todos los derechos reservados.",
  },
  privacidade: {
    titulo: "Política de privacidad",
    atualizado: "Actualizada en septiembre de 2026",
    blocos: [
      { titulo: "Qué recoge este sitio", texto: "Este sitio es estático y no usa cookies de rastreo, píxeles de publicidad ni analítica de terceros. Nada de lo que lees o simulas aquí sale de tu navegador." },
      { titulo: "El simulador", texto: "Los números que escribes en el simulador quedan solo en la memoria de tu navegador. Ninguno llega a Códice, salvo que elijas enviar la simulación por correo." },
      { titulo: "El formulario de contacto", texto: "El formulario arma un mensaje en tu propio programa de correo. Los datos solo salen de tu dispositivo cuando confirmas el envío." },
      { titulo: "Para qué lo usamos", texto: "Nombre, empresa, correo y mensaje se usan solo para responder y preparar la propuesta. No vendemos ni compartimos estos datos con terceros." },
      { titulo: "Datos en la operación", texto: "Los sensores de los displays hacen conteo agregado de flujo, sin reconocimiento facial y sin identificar al shopper. Ninguna persona es identificada en ninguna etapa." },
      { titulo: "Tus derechos", texto: "Puedes pedir acceso, corrección o eliminación de los datos que enviaste, conforme a la Ley General de Protección de Datos de Brasil. El pedido se atiende por el mismo correo de contacto." },
    ],
    voltar: "Volver al sitio",
  },
  erro404: {
    titulo: "Esta página salió del mapa.",
    texto: "La dirección que abriste ya no existe o nunca existió. Le pasa hasta a un display bien gestionado.",
    voltar: "Volver al inicio",
  },
};
