import type { Conteudo } from "./tipos";

/* Español. Refleja src/conteudo/pt.ts. */
export const es: Conteudo = {
  meta: {
    titulo: "Códice · Convierte el espacio de tu tienda en ingreso",
    descricao:
      "Códice alquila displays inteligentes por R$ 499 al mes. Tu cadena vende la semana de exposición a las marcas, con display, mantenimiento y plataforma incluidos.",
    palavras: "retail media, display de punto de venta, alquiler de display, trade marketing",
    ogAlt: "Display Códice instalado en un supermercado",
  },
  nav: {
    links: [
      { id: "como", rotulo: "Cómo funciona" },
      { id: "plataforma", rotulo: "Plataforma" },
      { id: "displays", rotulo: "Displays" },
      { id: "planos", rotulo: "Planes" },
      { id: "conta", rotulo: "Simulador" },
    ],
    cta: "Hablar con un especialista",
    abrirMenu: "Abrir menú",
    fecharMenu: "Cerrar menú",
    idioma: "Idioma",
    irParaConteudo: "Ir al contenido",
  },
  heroi: {
    chapeu: "Retail media para cadenas",
    titulo: ["Convierte el espacio de tu tienda en", "ingreso todos los meses"],
    lead: "Códice instala y mantiene el display. Tu cadena vende la semana de exposición a las marcas.",
    ctaPrimario: "Hablar con un especialista",
    ctaSecundario: "Simular mi cadena",
    selos: [
      { valor: "R$ 499", rotulo: "por display, por mes" },
      { valor: "1 cupo", rotulo: "paga 3 meses de alquiler" },
      { valor: "R$ 0", rotulo: "de inversión inicial" },
    ],
    legendaFoto: "Display Códice instalado en un supermercado",
  },
  prova: {
    frase: "Fábrica propia con 40 años de punto de venta y más de 15.000 puntos atendidos por el grupo.",
    marcas: "Marcas que las empresas del grupo ya atienden",
  },
  como: {
    chapeu: "Cómo funciona",
    titulo: "Tres pasos, un solo contrato",
    passos: [
      { n: "01", icone: "ferramenta", titulo: "Nosotros instalamos", texto: "Proyecto, producción y montaje en tienda, sin costo de entrada.", foto: "/fotos/foto-instalacao.jpg", alt: "Equipo técnico instalando el display en la tienda" },
      { n: "02", icone: "calendario", titulo: "Tu cadena vende", texto: "La marca compra la semana con la comunicación incluida.", foto: "/fotos/foto-ilha-supermercado.jpg", alt: "Display Códice con la campaña de una marca en un supermercado" },
      { n: "03", icone: "grafico", titulo: "Nosotros mantenemos y medimos", texto: "Mantenimiento, cambio de arte e informe con prueba de ejecución.", foto: "/fotos/foto-monitoramento.jpg", alt: "Central de monitoreo siguiendo la operación" },
    ],
    regra: "1 cupo = 1 semana de 1 display",
  },
  entrega: {
    chapeu: "Qué incluye",
    titulo: "Todo en la misma mensualidad",
    lead: "Sin costo aparte de proyecto, mantenimiento o software.",
    itens: [
      { icone: "display", titulo: "El display", texto: "Proyecto, fabricación y montaje." },
      { icone: "ferramenta", titulo: "Mantenimiento", texto: "Visita preventiva y reparación incluidas." },
      { icone: "calendario", titulo: "Cambio de arte", texto: "Comunicación nueva en cada campaña." },
      { icone: "grafico", titulo: "Plataforma", texto: "Agenda, reserva e informe." },
      { icone: "sensor", titulo: "Medición", texto: "Flujo y prueba de emisión." },
      { icone: "pessoas", titulo: "Apoyo comercial", texto: "Tarifa y material de venta." },
    ],
  },
  plataforma: {
    chapeu: "Plataforma",
    titulo: "Tu operación de medios en una pantalla",
    lead: "Agenda, campañas, flota y resultado en el mismo lugar.",
    telas: [
      { arquivo: "sis-painel", nome: "Panel", texto: "Ocupación, ingreso y plazos de la semana." },
      { arquivo: "sis-inventario", nome: "Inventario", texto: "Cada display se vuelve cupos semanales." },
      { arquivo: "sis-campanhas", nome: "Campañas", texto: "De la reserva a la salida al aire." },
      { arquivo: "sis-sensores", nome: "Sensores", texto: "Flujo medido tienda por tienda." },
      { arquivo: "sis-mapa", nome: "Mapa de la flota", texto: "Cada display en el mapa." },
      { arquivo: "sis-excecoes", nome: "Excepciones", texto: "Lo que se sale del plan se vuelve tarea." },
      { arquivo: "sis-campo", nome: "Modo campo", texto: "Inspección desde el celular, con QR." },
    ],
    ampliar: "Ampliar",
    fechar: "Cerrar",
    anterior: "Anterior",
    proxima: "Siguiente",
    aviso: "Pantallas reales del sistema, con datos de demostración.",
  },
  displays: {
    chapeu: "Displays",
    titulo: "Seis formatos, fabricados en Brasil",
    lead: "Un módulo se vuelve torre, doble o isla. La comunicación se cambia en cada campaña. Vea cada uno a tamaño real en la tienda con AR.",
    instrucao: "Gira y ve en AR",
    verAr: "Verlo a tamaño real (AR)",
    formatos: [
      { id: "torre", rotulo: "Torre", nome: "Torre", texto: "Módulo único: un frente de marca en el menor espacio.", medidas: "170 × 62 × 65 cm", ar: "https://projetos.75lab.com.br/ar/codice-display-universal/?modelo=torre" },
      { id: "duplo", rotulo: "Doble", nome: "Doble", texto: "Dos módulos lado a lado, dos frentes de marca.", medidas: "170 × 110 × 56 cm", ar: "https://projetos.75lab.com.br/ar/codice-display-universal/?modelo=duplo" },
      { id: "ilha", rotulo: "Isla", nome: "Isla (4 módulos)", texto: "Cuatro frentes de marca, alto impacto en el pasillo.", medidas: "170 × 111 × 112 cm", ar: "https://projetos.75lab.com.br/ar/codice-display-universal/?modelo=ilha" },
      { id: "ilha-frentes", rotulo: "2 frentes", nome: "Isla 2 frentes", texto: "Isla en dos grandes frentes de marca.", medidas: "170 × 112 × 112 cm", ar: "https://projetos.75lab.com.br/ar/codice-display-universal/?modelo=ilha-frentes" },
      { id: "baixa", rotulo: "Baja", nome: "Isla baja", texto: "90 cm de alto: no tapa la vista de la tienda.", medidas: "90 × 112 × 110 cm", ar: "https://projetos.75lab.com.br/ar/codice-display-universal/?modelo=baixa" },
      { id: "baixa-aereo", rotulo: "Baja + aéreo", nome: "Isla baja con aéreo", texto: "Isla baja con cabecera aérea, vista de lejos.", medidas: "118 × 112 × 110 cm", ar: "https://projetos.75lab.com.br/ar/codice-display-universal/?modelo=baixa-aereo" },
    ],
    acessoriosTitulo: "Accesorios",
    acessorios: [
      { nome: "Regla de precio", texto: "Acrílico con el arte de la marca, cambiado en cada campaña." },
      { nome: "Cabecera / comunicación", texto: "Cabecera impresa que identifica la marca en el punto." },
      { nome: "Módulo aéreo", texto: "Cabecera elevada, visible desde el otro lado de la tienda." },
    ],
    marcasTitulo: "Ejemplos de marca",
    marcas: [
      { nome: "Lacta", ar: "https://projetos.75lab.com.br/ar/codice-display-universal/?modelo=lacta" },
      { nome: "Bis", ar: "https://projetos.75lab.com.br/ar/codice-display-universal/?modelo=bis" },
      { nome: "Pedigree / Whiskas", ar: "https://projetos.75lab.com.br/ar/codice-display-universal/?modelo=pedigree-whiskas" },
    ],
  },
  planos: {
    chapeu: "Planes",
    titulo: "Elige cuánto debe medir el display",
    lead: "Cuanto más prueba el display, más cobra la cadena por el cupo.",
    porMes: "por display, por mes",
    itens: [
      {
        id: "essencial", nome: "Essencial", preco: 499, selo: "Para empezar", quem: "Vender espacio ya, con baja complejidad.",
        recursos: [
          { icone: "display", texto: "Display modular" },
          { icone: "calendario", texto: "Comunicación intercambiable" },
          { icone: "qr", texto: "QR patrimonial" },
          { icone: "ferramenta", texto: "Mantenimiento incluido" },
        ],
      },
      {
        id: "sense", nome: "Sense", preco: 849, selo: "El más elegido", quem: "Puntos de alto flujo, con prueba de paso.",
        recursos: [
          { icone: "check", texto: "Todo lo del Essencial" },
          { icone: "pessoas", texto: "Sensor de proximidad" },
          { icone: "wifi", texto: "Alertas de conexión" },
          { icone: "grafico", texto: "Panel de ejecución" },
        ],
      },
      {
        id: "media", nome: "Media", preco: 1290, selo: "Mayor valor por cupo", quem: "Lanzamientos y campañas con video en tienda.",
        recursos: [
          { icone: "check", texto: "Todo lo del Sense" },
          { icone: "tela", texto: "Pantalla y player" },
          { icone: "calendario", texto: "Contenido remoto" },
          { icone: "escudo", texto: "Prueba de emisión" },
        ],
      },
    ],
    cta: "Quiero este plan",
    nota: "Instalación, mantenimiento y plataforma incluidos en todos los planes.",
  },
  conta: {
    chapeu: "La cuenta",
    titulo: "Suscribirse cuesta 86% menos el primer mes",
    lead: "Comprar exige capital antes de la primera venta. Suscribirse no.",
    comprar: { titulo: "Comprar por cuenta propia", valor: 3620, nota: "Display, instalación y operación en el 1er mes." },
    assinar: { titulo: "Suscribirse a Códice", valor: 499, nota: "Todo incluido, sin capital inmovilizado.", selo: "86% menos" },
    grafico: {
      titulo: "Desembolso acumulado por display, en 12 meses",
      serieComprar: "Comprar por cuenta propia",
      serieAssinar: "Suscribirse a Códice",
      virada: "La compra pasa a acumular menos",
      mes: "M",
    },
    argumento: [
      "Ningún capital parado antes de vender el primer cupo.",
      "Mantenimiento, cambio de arte y plataforma siempre incluidos.",
      "Tecnología que evoluciona por capa, sin nueva compra.",
    ],
    simulador: {
      titulo: "Simula tu cadena",
      campos: { lojas: "Tiendas", displays: "Displays por tienda", cota: "Precio del cupo", ocupacao: "Agenda vendida" },
      saidas: { receita: "Ingreso con cupos", aluguel: "Alquiler Códice", lucro: "Ganancia en 12 meses" },
      periodo: "Proyección de 12 meses",
      nota: "Valores antes de impuestos. Mes promedio de 4,3 semanas.",
      cta: "Enviar esta simulación",
    },
  },
  numeros: {
    itens: [
      { valor: 40, sufixo: "+", rotulo: "años de fabricación" },
      { valor: 15000, sufixo: "+", rotulo: "puntos atendidos por el grupo" },
      { valor: 6, sufixo: "", rotulo: "formatos de display" },
      { valor: 100, sufixo: "%", rotulo: "producción en Brasil" },
    ],
    nota: "Números de las empresas del grupo: NeoBand en la fabricación y 75 LAB en trade y tecnología.",
  },
  faq: {
    chapeu: "Preguntas",
    titulo: "Lo que preguntan antes de cerrar",
    itens: [
      { pergunta: "¿Necesito comprar algo para empezar?", resposta: "No. Display, instalación, mantenimiento y plataforma entran en la mensualidad de R$ 499 por display." },
      { pergunta: "¿Quién vende el cupo a la industria?", resposta: "La cadena vende su propio espacio y se queda con el ingreso. Códice entrega la tarifa, la agenda y la prueba de ejecución, y apoya la conversación cuando se lo piden." },
      { pergunta: "¿El sensor identifica a las personas?", resposta: "No. El conteo es agregado, sin cámara de reconocimiento y sin identificar al shopper. El sistema informa paso y permanencia aproximada." },
      { pergunta: "¿Y si el display se rompe?", resposta: "Mantenimiento y reparación están en la mensualidad. El display avisa cuando pierde conexión y la incidencia se vuelve tarea con plazo." },
      { pergunta: "¿Se puede empezar con pocas tiendas?", resposta: "Sí. El contrato es por display, así que la cadena empieza por una plaza, mide el resultado y amplía después." },
      { pergunta: "¿En cuánto tiempo se paga?", resposta: "Un cupo de R$ 1.500 cubre tres meses del plan Essencial. El simulador de arriba muestra la ganancia de tu cadena en doce meses." },
    ],
  },
  conversao: {
    chapeu: "Habla con nosotros",
    titulo: "Recibe la propuesta con los números de tu cadena",
    lead: "Respondemos el mismo día hábil.",
    campos: { nome: "Nombre", empresa: "Cadena", email: "Correo", lojas: "Número de tiendas", mensagem: "Mensaje" },
    enviar: "Quiero la propuesta",
    enviando: "Preparando",
    sucesso: "Listo para enviar",
    sucessoDetalhe: "Abrimos tu correo con el mensaje escrito. Si no se abrió nada, escribe a",
    erro: "Revisa los campos destacados",
    whatsapp: "Hablar por WhatsApp",
    email: "Escribir un correo",
    consentimento: "Usamos tus datos solo para responder a este contacto.",
  },
  rodape: {
    frase: "Displays inteligentes para grandes resultados.",
    navegacao: "Navegación",
    contato: "Contacto",
    privacidade: "Política de privacidad",
    creditos: "Fabricación NeoBand. Trade y tecnología 75 LAB.",
    direitos: "Todos los derechos reservados.",
  },
  privacidade: {
    titulo: "Política de privacidad",
    atualizado: "Actualizada en septiembre de 2026",
    blocos: [
      { titulo: "Qué recoge este sitio", texto: "Este sitio es estático y no usa cookies de rastreo, píxeles de publicidad ni analítica de terceros." },
      { titulo: "El simulador", texto: "Los números que escribes quedan en tu navegador y solo se envían si eliges mandar la simulación por correo." },
      { titulo: "El formulario", texto: "El formulario arma el mensaje en tu propio programa de correo. Los datos solo salen de tu dispositivo cuando confirmas el envío." },
      { titulo: "Para qué lo usamos", texto: "Nombre, cadena, correo y mensaje sirven solo para responder al contacto y preparar la propuesta." },
      { titulo: "Datos en la operación", texto: "Los sensores hacen conteo agregado de flujo, sin reconocimiento facial y sin identificar al shopper." },
      { titulo: "Tus derechos", texto: "Puedes pedir acceso, corrección o eliminación de los datos enviados, conforme a la Ley General de Protección de Datos de Brasil." },
    ],
    voltar: "Volver al sitio",
  },
  erro404: {
    titulo: "Esta página salió del mapa",
    texto: "La dirección que abriste ya no existe o nunca existió.",
    voltar: "Volver al inicio",
  },
};
