import type { Conteudo } from "./tipos";

/* Português do Brasil. Título curto, uma frase de apoio, nada além disso. */
export const pt: Conteudo = {
  meta: {
    titulo: "Códice · Transforme o espaço da sua loja em receita",
    descricao:
      "A Códice aluga displays inteligentes por R$ 499 ao mês. A sua rede vende a semana de exposição para as marcas, com display, manutenção e plataforma inclusos.",
    palavras: "retail media, display de PDV, aluguel de display, mídia de varejo, trade marketing",
    ogAlt: "Display Códice instalado em supermercado",
  },
  nav: {
    links: [
      { id: "como", rotulo: "Como funciona" },
      { id: "plataforma", rotulo: "Plataforma" },
      { id: "displays", rotulo: "Displays" },
      { id: "planos", rotulo: "Planos" },
      { id: "conta", rotulo: "Simulador" },
    ],
    cta: "Falar com um especialista",
    abrirMenu: "Abrir menu",
    fecharMenu: "Fechar menu",
    idioma: "Idioma",
    irParaConteudo: "Ir para o conteúdo",
  },
  heroi: {
    chapeu: "Retail media para o varejo",
    titulo: ["Transforme o espaço da sua loja em", "receita todo mês"],
    lead: "A Códice instala e mantém o display. A sua rede vende a semana de exposição para as marcas.",
    ctaPrimario: "Falar com um especialista",
    ctaSecundario: "Simular a minha rede",
    selos: [
      { valor: "R$ 499", rotulo: "por display, por mês" },
      { valor: "1 cota", rotulo: "paga 3 meses de aluguel" },
      { valor: "R$ 0", rotulo: "de investimento inicial" },
    ],
    legendaFoto: "Display Códice instalado em supermercado",
  },
  prova: {
    frase: "Fabricação própria com 40 anos de ponto de venda e mais de 15.000 PDVs atendidos pelo grupo.",
    marcas: "Marcas que as empresas do grupo já atendem",
  },
  como: {
    chapeu: "Como funciona",
    titulo: "Três passos, um contrato só",
    passos: [
      {
        n: "01",
        icone: "ferramenta",
        titulo: "A gente instala",
        texto: "Projeto, produção e montagem na loja, sem custo de entrada.",
        foto: "/fotos/foto-instalacao.jpg",
        alt: "Equipe técnica instalando o display na loja",
      },
      {
        n: "02",
        icone: "calendario",
        titulo: "A sua rede vende",
        texto: "A marca compra a semana com a comunicação inclusa.",
        foto: "/fotos/foto-ilha-supermercado.jpg",
        alt: "Display Códice com a campanha de uma marca em supermercado",
      },
      {
        n: "03",
        icone: "grafico",
        titulo: "A gente mantém e mede",
        texto: "Manutenção, troca de arte e relatório com prova de execução.",
        foto: "/fotos/foto-monitoramento.jpg",
        alt: "Central de monitoramento acompanhando a operação",
      },
    ],
    regra: "1 cota = 1 semana de 1 display",
  },
  entrega: {
    chapeu: "O que está incluso",
    titulo: "Tudo na mesma mensalidade",
    lead: "Sem custo de projeto, de manutenção ou de software.",
    itens: [
      { icone: "display", titulo: "O display na loja", texto: "Projeto, fabricação e montagem." },
      { icone: "ferramenta", titulo: "Manutenção", texto: "Visita preventiva e reparo inclusos." },
      { icone: "calendario", titulo: "Troca de comunicação", texto: "Arte nova a cada campanha." },
      { icone: "grafico", titulo: "Plataforma", texto: "Agenda, reserva e relatório." },
      { icone: "sensor", titulo: "Medição", texto: "Fluxo e prova de veiculação." },
      { icone: "pessoas", titulo: "Apoio comercial", texto: "Tabela e material de venda." },
    ],
  },
  plataforma: {
    chapeu: "Plataforma",
    titulo: "A sua operação de mídia em uma tela",
    lead: "Agenda, campanhas, frota e resultado no mesmo lugar.",
    telas: [
      { arquivo: "sis-painel", nome: "Painel", texto: "Ocupação, receita e prazos da semana." },
      { arquivo: "sis-inventario", nome: "Inventário", texto: "Cada display vira cotas semanais." },
      { arquivo: "sis-campanhas", nome: "Campanhas", texto: "Da reserva à veiculação." },
      { arquivo: "sis-sensores", nome: "Sensores", texto: "Fluxo medido loja a loja." },
      { arquivo: "sis-mapa", nome: "Mapa da frota", texto: "Cada display no mapa." },
      { arquivo: "sis-excecoes", nome: "Exceções", texto: "O que saiu do plano vira tarefa." },
      { arquivo: "sis-campo", nome: "Modo campo", texto: "Vistoria pelo celular, com QR." },
    ],
    ampliar: "Ampliar",
    fechar: "Fechar",
    anterior: "Anterior",
    proxima: "Próxima",
    aviso: "Telas reais do sistema, com dados de demonstração.",
  },
  displays: {
    chapeu: "Displays",
    titulo: "Seis formatos, fabricados no Brasil",
    lead: "Estrutura modular e comunicação cambiável a cada campanha.",
    instrucao: "Arraste para girar",
    formatos: [
      { id: "essencial", rotulo: "Ponta", nome: "Ponta de gôndola", texto: "O ponto mais disputado da loja.", medidas: "202 × 104 × 55 cm" },
      { id: "ilha", rotulo: "Ilha", nome: "Ilha dupla face", texto: "Duas frentes de venda no corredor largo.", medidas: "190 × 120 × 96 cm" },
      { id: "painel", rotulo: "Painel", nome: "Painel de acessórios", texto: "Ganchos para item pequeno de alto valor.", medidas: "195 × 122 × 42 cm" },
      { id: "vitrine", rotulo: "Vitrine", nome: "Vitrine premium", texto: "Vidro que protege o produto e valoriza a cota.", medidas: "192 × 122 × 54 cm" },
      { id: "categoria", rotulo: "Categoria", nome: "Expositor de categoria", texto: "Prateleiras com faixa de marca na base.", medidas: "200 × 100 × 46 cm" },
      { id: "multiuso", rotulo: "Multiuso", nome: "Multiuso com gavetas", texto: "Exposição em cima, estoque embaixo.", medidas: "195 × 74 × 52 cm" },
    ],
  },
  planos: {
    chapeu: "Planos",
    titulo: "Escolha quanto o display precisa medir",
    lead: "Quanto mais o display prova, mais a rede cobra pela cota.",
    porMes: "por display, por mês",
    itens: [
      {
        id: "essencial",
        nome: "Essencial",
        preco: 499,
        selo: "Para começar",
        quem: "Vender espaço já, com baixa complexidade.",
        recursos: [
          { icone: "display", texto: "Display modular" },
          { icone: "calendario", texto: "Comunicação cambiável" },
          { icone: "qr", texto: "QR patrimonial" },
          { icone: "ferramenta", texto: "Manutenção inclusa" },
        ],
      },
      {
        id: "sense",
        nome: "Sense",
        preco: 849,
        selo: "Mais vendido",
        quem: "Pontos de alto fluxo, com prova de passagem.",
        recursos: [
          { icone: "check", texto: "Tudo do Essencial" },
          { icone: "pessoas", texto: "Sensor de proximidade" },
          { icone: "wifi", texto: "Alertas de conexão" },
          { icone: "grafico", texto: "Painel de execução" },
        ],
      },
      {
        id: "media",
        nome: "Media",
        preco: 1290,
        selo: "Maior valor por cota",
        quem: "Lançamentos e campanhas com vídeo na loja.",
        recursos: [
          { icone: "check", texto: "Tudo do Sense" },
          { icone: "tela", texto: "Tela e player" },
          { icone: "calendario", texto: "Conteúdo remoto" },
          { icone: "escudo", texto: "Prova de veiculação" },
        ],
      },
    ],
    cta: "Quero este plano",
    nota: "Instalação, manutenção e plataforma inclusas em todos os planos.",
  },
  conta: {
    chapeu: "A conta",
    titulo: "Assinar custa 86% menos no primeiro mês",
    lead: "Comprar exige capital antes da primeira venda. Assinar não.",
    comprar: { titulo: "Comprar sozinho", valor: 3620, nota: "Display, instalação e operação no 1º mês." },
    assinar: { titulo: "Assinar a Códice", valor: 499, nota: "Tudo incluso, sem capital imobilizado.", selo: "86% menos" },
    grafico: {
      titulo: "Desembolso acumulado por display, em 12 meses",
      serieComprar: "Comprar sozinho",
      serieAssinar: "Assinar a Códice",
      virada: "A compra passa a acumular menos",
      mes: "M",
    },
    argumento: [
      "Nenhum capital parado antes de vender a primeira cota.",
      "Manutenção, troca de arte e plataforma sempre inclusas.",
      "Tecnologia que evolui por camada, sem nova compra.",
    ],
    simulador: {
      titulo: "Simule a sua rede",
      campos: { lojas: "Lojas", displays: "Displays por loja", cota: "Preço da cota", ocupacao: "Agenda vendida" },
      saidas: { receita: "Receita com cotas", aluguel: "Aluguel Códice", lucro: "Lucro em 12 meses" },
      periodo: "Projeção de 12 meses",
      nota: "Valores antes de impostos. Mês médio de 4,3 semanas.",
      cta: "Enviar esta simulação",
    },
  },
  numeros: {
    itens: [
      { valor: 40, sufixo: "+", rotulo: "anos de fabricação" },
      { valor: 15000, sufixo: "+", rotulo: "PDVs atendidos pelo grupo" },
      { valor: 6, sufixo: "", rotulo: "formatos de display" },
      { valor: 100, sufixo: "%", rotulo: "produção no Brasil" },
    ],
    nota: "Números das empresas do grupo: NeoBand na fabricação e 75 LAB no trade e na tecnologia.",
  },
  faq: {
    chapeu: "Dúvidas",
    titulo: "O que perguntam antes de fechar",
    itens: [
      {
        pergunta: "Preciso comprar alguma coisa para começar?",
        resposta: "Não. Display, instalação, manutenção e plataforma entram na mensalidade de R$ 499 por display.",
      },
      {
        pergunta: "Quem vende a cota para a indústria?",
        resposta: "A rede vende o próprio espaço e fica com a receita. A Códice entrega a tabela, a agenda e a prova de execução, e apoia na conversa quando a rede pede.",
      },
      {
        pergunta: "O sensor identifica as pessoas?",
        resposta: "Não. A contagem é agregada, sem câmera de reconhecimento e sem identificar o shopper. O sistema informa passagem e permanência aproximada.",
      },
      {
        pergunta: "E se o display quebrar?",
        resposta: "Manutenção e reparo estão na mensalidade. O display avisa quando perde conexão e a ocorrência vira tarefa com prazo.",
      },
      {
        pergunta: "Dá para começar com poucas lojas?",
        resposta: "Dá. O contrato é por display, então a rede começa por uma praça, mede o resultado e amplia depois.",
      },
      {
        pergunta: "Em quanto tempo se paga?",
        resposta: "Uma cota de R$ 1.500 cobre três meses do plano Essencial. O simulador acima mostra o lucro da sua rede em doze meses.",
      },
    ],
  },
  conversao: {
    chapeu: "Fale com a gente",
    titulo: "Receba a proposta com os números da sua rede",
    lead: "Respondemos no mesmo dia útil.",
    campos: { nome: "Nome", empresa: "Rede", email: "E-mail", lojas: "Número de lojas", mensagem: "Mensagem" },
    enviar: "Quero a proposta",
    enviando: "Preparando",
    sucesso: "Tudo pronto para enviar",
    sucessoDetalhe: "Abrimos o seu e-mail com a mensagem escrita. Se nada abrir, escreva para",
    erro: "Confira os campos destacados",
    whatsapp: "Falar pelo WhatsApp",
    email: "Escrever um e-mail",
    consentimento: "Usamos os seus dados apenas para responder a este contato.",
  },
  rodape: {
    frase: "Displays inteligentes para grandes resultados.",
    navegacao: "Navegação",
    contato: "Contato",
    privacidade: "Política de privacidade",
    creditos: "Fabricação NeoBand. Trade e tecnologia 75 LAB.",
    direitos: "Todos os direitos reservados.",
  },
  privacidade: {
    titulo: "Política de privacidade",
    atualizado: "Atualizada em setembro de 2026",
    blocos: [
      { titulo: "O que este site coleta", texto: "Este site é estático e não usa cookie de rastreamento, pixel de publicidade nem analytics de terceiros." },
      { titulo: "O simulador", texto: "Os números que você digita ficam apenas no seu navegador e só são enviados se você escolher mandar a simulação por e-mail." },
      { titulo: "O formulário", texto: "O formulário monta a mensagem no seu próprio programa de e-mail. Os dados só saem do seu dispositivo quando você confirma o envio." },
      { titulo: "Para que usamos", texto: "Nome, rede, e-mail e mensagem servem apenas para responder ao contato e preparar a proposta." },
      { titulo: "Dados na operação", texto: "Os sensores dos displays fazem contagem agregada de fluxo, sem reconhecimento facial e sem identificar o shopper." },
      { titulo: "Seus direitos", texto: "Você pode pedir acesso, correção ou exclusão dos dados enviados, conforme a Lei Geral de Proteção de Dados." },
    ],
    voltar: "Voltar para o site",
  },
  erro404: {
    titulo: "Esta página saiu do mapa",
    texto: "O endereço que você abriu não existe mais ou nunca existiu.",
    voltar: "Voltar para o início",
  },
};
